import  "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
//import "../styles/custom-bootstrap.scss";
// import "../styles/swiper-bundle.min.css"
// import "../styles/glightbox.min.css"
// import "../styles/aos.css"
import AddBootstrap from "./AddBootstrap";
import Header from "@/components/header/Header";
import Head from "next/head";
import Footer from "@/components/footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&amp;family=Nunito:wght@300;400;500;600;700&amp;display=swap" rel="stylesheet" />
      {/* <link rel="stylesheet" href="/assets/css/plugins/swiper-bundle.min.css" />
        <link rel="stylesheet" href="/assets/css/plugins/glightbox.min.css" />
        <link rel="stylesheet" href="/assets/css/plugins/aos.css" /> */}
      </Head>
      <body>
        <AddBootstrap />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
