// //import  "bootstrap/dist/css/bootstrap.min.css"
// import "swiper/css";
// import "swiper/css/navigation";
// import "swiper/css/pagination";
// import "@/app/styles/custom-bootstrap.scss";
// import "./globals.css";
// //import "../styles/custom.css";
// import "@/app/styles/custom.css";

// // import "../styles/swiper-bundle.min.css"
// // import "../styles/glightbox.min.css"
// // import "../styles/aos.css"
// import AddBootstrap from "./AddBootstrap";
// import Header from "@/components/header/Header";
// import Head from "next/head";
// import Footer from "@/components/footer/Footer";
// import Providers from "./progressBarprovider";
// import SocialMediaFooter from "@/components/common/SocialMediaFooter";
// import AppSessionProvider from "./AppSessionProvider";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <Head>
//         <link
//           href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&amp;family=Nunito:wght@300;400;500;600;700&amp;display=swap"
//           rel="stylesheet"
//         />
//         {/* <script
//           src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyDLzo_eOh509ONfCjn1XQp0ZM2pacPdnWc&libraries=places`}
          
//         /> */}
//         {/* <link rel="stylesheet" href="/assets/css/plugins/swiper-bundle.min.css" />
//         <link rel="stylesheet" href="/assets/css/plugins/glightbox.min.css" />
//         <link rel="stylesheet" href="/assets/css/plugins/aos.css" /> */}
//       </Head>
//       <body>
//         <AddBootstrap />
//         {/* <AppSessionProvider> */}
//         <Providers>
          
//           {/* <Header /> */}
//           {children}
//           <SocialMediaFooter />
//           <Footer />
          
//         </Providers>
//         {/* </AppSessionProvider> */}
//       </body>
//     </html>
//   );
// }



//import  "bootstrap/dist/css/bootstrap.min.css"
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "@/app/styles/custom-bootstrap.scss";
import "./globals.css";
//import "../styles/custom.css";
import "@/app/styles/custom.css";
// import "../styles/swiper-bundle.min.css"
// import "../styles/glightbox.min.css"
// import "../styles/aos.css"
import AddBootstrap from "./AddBootstrap";
import Header from "@/components/header/Header";
import Head from "next/head";
import Footer from "@/components/footer/Footer";
import Providers from "./progressBarprovider";
import SocialMediaFooter from "@/components/common/SocialMediaFooter";

export const metadata = {
  title: "LandmarkPlots - Buy, Rent, Sell Your Ideal Property Today",
  description: "Discover your dream property with LandmarkPlots.com, a premier platform offering exclusive land and real estate opportunities. Explore a curated selection of prime plots, residential, and commercial properties tailored to your needs.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <meta name="google-site-verification" content="3PcL6iH5Cja8l2D6155wrCas1jpJh7BM9PKFupsa0ZQ" />
      <Head>
    
        <link rel="preload" fetchpriority="high" as="image" href="/assets/img/hero/hero-banner.webp" type="image/webp" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&amp;family=Nunito:wght@300;400;500;600;700&amp;display=swap"
          rel="stylesheet"
        />
        {/* <script
          src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyDLzo_eOh509ONfCjn1XQp0ZM2pacPdnWc&libraries=places`}
          
        /> */}
        {/* <link rel="stylesheet" href="/assets/css/plugins/swiper-bundle.min.css" />
        <link rel="stylesheet" href="/assets/css/plugins/glightbox.min.css" />
        <link rel="stylesheet" href="/assets/css/plugins/aos.css" /> */}
      </Head>
      <body>
        <AddBootstrap />
        <Providers>
          <Header />
          {children}
          <SocialMediaFooter />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}